### ISSUE TITLE
script terminates after installing a package from niksula.hut.fi/~mhiienka

### ISSUE THREAD

**Issue by spiritfromz** [emmercm/rpi-headers#1]
Hi Christian,

I'm trying rpi-headers on a fresh Raspbian installed through the latest NOOBS (kernel 4.4.11+). No rpi-update was done. 
The script goes through  _niksula.hut.fi/~mhiienka_ code path. After downloading and installing the linux-headers package, there are some unsatisfied dependencies left (gcc-4.7). It tries to install them, but terminates at _`sudo apt-get -y check > /dev/null`_ line. Not sure what's the point of this line, as the next line should install the missing dependencies.

```
Checking apt-cache for linux-headers-4.4.11+ ...
   Running apt-get update ...
   Did not find package

Checking http://niksula.hut.fi/~mhiienka for linux-headers-4.4.11+ ...
   Downloading linux-headers-4.4.11+_4.4.11+-2_armhf.deb ...
   Installing package ...
dpkg: dependency problems prevent configuration of linux-headers-4.4.11+:
 linux-headers-4.4.11+ depends on gcc-4.7; however:
  Package gcc-4.7 is not installed.

dpkg: error processing package linux-headers-4.4.11+ (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 linux-headers-4.4.11+
   Installing apt-get missing dependencies ...
E: Unmet dependencies. Try using -f.

```

P.S. I did _`sudo apt-get install wget git make gcc bc dkms`_ before running rpi-headers.

**Comment by emmercm** [comment]
Apologies for the exceptionally late response. The intention of that APT block is a "just in case / for good measure", but it is only meant for when dpkg succeeds. It looks like I need to find a better way to do success checking rather than checking for "modules.order".

**Comment by emmercm** [comment]
Even with gcc-4.7 I can't get **linux-headers-4.4.11-v7+_4.4.11-v7+-2_armhf.deb** to build on a Raspberry Pi 3 with a fresh NOOBS 1.9.2 / Raspbrian 4.4.11-v7+. Trying to find a version to build correctly without extra work.

**Comment by emmercm** [comment]
Doing a apt-get upgrade/dist-upgrade brings it up to 4.4.13-v7+ and there isn't a deb package available for that.

Running a rpi-update brings it up to 4.4.22-v7+, and the deb package for that installs without any problems with gcc-4.7. Changed the success detection described above so it should be more accurate, updated install instructions in README.
